server.port=9090
spring.data.mongodb.uri=mongodb+srv://paragkushwah4_db_user:FKSKMkz8VfuH7Eys@cluster0.vgov8jm.mongodb.net/employeedb?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true


